---
# Training configs
config_file: "configs/PDwRN.yaml"
data_path: "/home/myeghiaz/Project/PDwRN/data/"
info_update_period: 10

# Evaluation configs
compute_AP: True
conf_thresh: 0.000001
test_dataset: "LINZ_train"

# Training + Evaluation configs
debug_on: False